all:
	# xelatex --shell-escape -draftmode --interaction=nonstopmode -output-directory=build main.tex
	# biber --input-directory=build main
	xelatex --shell-escape --interaction=nonstopmode -output-directory=build main.tex
	ln -sf build/main.pdf .
